# : Manager [[[

[mgr]
cwd = { fg = "#dee4e0" }

# Tab
tab_active = { fg = "#00382d", bg = "#86d6be", bold = true }
tab_inactive = { fg = "#a2f2da", bg = "#002019" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#5fbdff", bg = "#5fbdff" }
marker_cut = { fg = "#c5e7ff", bg = "#c5e7ff" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#a9cbe3", bg = "#a9cbe3" }

# Count
count_copied = { fg = "#001e2d", bg = "#c5e7ff" }
count_cut = { fg = "#001e2d", bg = "#c5e7ff" }
count_selected = { fg = "#00382d", bg = "#a9cbe3" }

# Border
border_symbol = "‚îÇ"
border_style  = { fg = "#86d6be" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#00382d", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#86d6be", fg = "#00382d", bold = true }
normal_alt  = { bg = "#3f4945", fg = "#bfc9c4" }

# Select mode
select_main = { bg = "#b2ccc2", fg = "#1d352e", bold = true }
select_alt  = { bg = "#3f4945", fg = "#bfc9c4" }

# Unset mode
unset_main = { bg = "#a9cbe3", fg = "#0f3447", bold = true }
unset_alt  = { bg = "#3f4945", fg = "#bfc9c4" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#86d6be", bg = "#343b38" }
progress_error = { fg = "#ffb4ab", bg = "#343b38" }

# Permissions
permissions_t = { fg = "#5b8a78" }
permissions_w = { fg = "#3c84b7" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#2ca8ff" }
permissions_s = { fg = "#1fdca3" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#86d6be" }
active = { fg = "#a9cbe3", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#86d6be" }
value = { fg = "#dee4e0" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#86d6be", bg = "#00382d" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#86d6be" }
title = {}
hovered = { fg = "#c5e7ff", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#343b38" }
cand = { fg = "#86d6be" }
rest = { fg = "#00382d" }
desc = { fg = "#dee4e0" }
separator = " ‚ñ∂ "
separator_style = { fg = "#dee4e0" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#dee4e0" }
run = { fg = "#dee4e0" }
footer = { fg = "#1d352e", bg = "#b2ccc2" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#a9cbe3" }
title_warn = { fg = "#86d6be" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#dee4e0" },
    { name = "*/", fg = "#86d6be" },
]

# : ]]]
